package de.tum.in.tumcampusapp.auxiliary;

public final class Const {

	public static final class Settings {
		public static final String APP_DETAILS_SETTINGS_KEY = "app_details";
		public final static String cafeteriaFilter = "cafeteriaFilter";
		public final static String debug = "debug";
		public static final String MARKET_SETTINGS_KEY = "market";
		public final static String silence = "silence";
		public final static String silence_on = "silence_on";
		public static final String TUMONLINE_SETTINGS_KEY = "tumonline";
	}

	public static final int HTTP_TIMEOUT = 25000;
	public static final String ACCESS_TOKEN = "access_token";
	public static final String ACTION_EXTRA = "action";
	public static final String ADDRESS_COLUMN = "address";
	public static final String CAFETERIA_ID = "cafeteriasId";
	public static final String CAFETERIA_NAME = "cafeteriasName";
	public static final String CAFETERIAS = "cafeterias";
	public static final String COMPLETED = "completed";
	public static final String CURRICULA = "curricula";
	public static final String DATE = "date";
	public static final String DATE_COLUMN_DE = "date_de";
	public final static String db = "database.db";
	public final static int dbVersion = 1;
	public static final String DE = "de";
	public static final String DEFAULTS = "defaults";
	public static final String DESCRIPTION_COLUMN = "description";
	public static final String DOCUMENTS = "documents";
	public static final String EN = "en";
	public static final String END_DE_COLUMN = "end_de";
	public static final String END_DT_COLUMN = "end_dt";
	public static final String ERROR = "error";
	public static final String ERROR_MESSAGE = "error_message";
	public static final String EVENTS = "events";
	public static final String FACEBOOK = "www.facebook.com";
	public static final String FEED_ID = "feedId";
	public static final String FEED_NAME = "feedName";
	public static final String FEEDS = "feeds";
	public static final String GALLERY = "gallery";
	public static final String HOLIDAY = "holiday";
	public static final String HOURS_COLUMN = "hours";
	public static final String ID_COLUMN = "_id";
	public static final String ID_EXTRA = "id";
	public static final String IMAGE_COLUMN = "image";
	public static final String LECTURE_ID_COLUMN = "lectureId";
	public static final String LECTURES = "lectures";
	public static final String LECTURES_APPOINTMENTS = "veranstaltungenTermine";
	public static final String LECTURES_DETAILS = "veranstaltungenDetails";
	public static final String LECTURES_PERSONAL = "veranstaltungenEigene";
	public static final String LECTURES_SEARCH = "veranstaltungenSuche";
	public static final String LECTURES_TUM_ONLINE = "lecturesTUMOnline";
	public static final String LINK_COLUMN = "link";
	public static final String LINKS = "links";
	public static final String LOCATION_COLUMN = "location";
	public static final String LRZ_ID = "lrz_id";
	public static final String MESSAGE_EXTRA = "message";
	public static final String MODULE_COLUMN = "module";
	public static final String NAME_COLUMN = "name";
	public static final String NEWS = "news";
	public static final String NOTE_COLUMN = "note";
	public static final String NOTEN = "noten";
	public static final String ORG_ID = "orgId";
	public static final String ORG_NAME = "orgName";
	public static final String ORG_PARENT_ID = "orgParentId";
	public static final String ORGANISATIONS = "organisations";
	public static final String REMARK_COLUMN = "remark";
	public static final String ROOM_COLUMN = "room";
	public static final String ROOMFINDER = "roomfinder";
	public static final String START_DE_COLUMN = "start_de";
	public static final String START_DT_COLUMN = "start_dt";
	public static final String STUDIENBEITRAGSTATUS = "studienbeitragsstatus";
	public static final String TITLE_EXTRA = "title";
	public static final String TRANSPORT_COLUMN = "transport";
	public static final String TUMONLINE_PASSWORD = "tumonline_password";
	public static final String URL = "url";
	public static final String URL_COLUMN = "url";
	public static final String VACATION = "vacation";
	public static final String WEEKDAY_COLUMN = "weekday";
}